### ISSUE TITLE
Inconsistent final plan when accessing kube raw config

### ISSUE THREAD

**Issue by francocatena** [terraform-providers/terraform-provider-digitalocean#244] opened 2019-05-29 22:31 UTC
Hi,

After upgradiing to version 1.4.0, I now have an "inconsistent final plan error". It is related to the "changing nature" of the kube config content. It seems the content should be marked as "computed" according to the Compatibility Guide: https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#inaccurate-plans.

### Terraform Version
Terraform v0.12.0
+ provider.digitalocean v1.4.0
+ provider.kubernetes v1.7.0
+ provider.local v1.2.2

### Affected Resource(s)
- digitalocean_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "local_file" "kubernetes_config" {
  content  = digitalocean_kubernetes_cluster.k8s-cirope.kube_config.0.raw_config
  filename = "kubeconfig.yaml"
}
```

### Debug Output
https://gist.github.com/8739d02619d39485f54112e179c6b071

I only changed the certificates data for strings like "DATAXXX" or "DATAYYY". Otherwise, is the original output.

### Expected Behavior
It should create kubeconfig.yml. With version 0.11.0 of Terraform this was the behaviour.

### Actual Behavior
It showed an error and didn't create the file.

### Steps to Reproduce
1. `terraform apply`

**Comment by andrewsomething** [comment] 2019-05-30 18:18
Hi @francocatena, thanks for the report. I haven't been able to reproduce this

> It seems the content should be marked as "computed" according to the Compatibility Guide

The kubeconfig attributes are marked as "computed" See:

https://github.com/terraform-providers/terraform-provider-digitalocean/blob/90ff3d362d0bf9749de3ad3833eeb205a543d71d/digitalocean/resource_digitalocean_kubernetes_cluster.go#L107-L110

Using this minimal example, I am able to successfully run `terraform apply` and the `kubeconfig.yml` file is created.  Can you share an example config that demonstrates this issue?

```hcl
resource "digitalocean_kubernetes_cluster" "example" {
  name    = "example-01"
  region  = "nyc1"
  version = "1.14.2-do.0"

  node_pool {
    name       = "example"
    size       = "s-1vcpu-2gb"
    node_count = 3
  }
}

resource "local_file" "kubernetes_config" {
  content  = digitalocean_kubernetes_cluster.example.kube_config.0.raw_config
  filename = "kubeconfig.yaml"
}
```

Though it does recreate the local file on each run despite the actual contents not changing which is not ideal. So there is definitely more to dig into with this.

```
Terraform will perform the following actions:

  # local_file.kubernetes_config must be replaced
-/+ resource "local_file" "kubernetes_config" {
      ~ content  = <<~EOT # forces replacement
```

**Comment by francocatena** [comment] 2019-06-03 18:22
Hi @andrewsomething,

I can reproduce it with the following config:

```hcl
resource "digitalocean_kubernetes_cluster" "k8s-cirope-test" {
  name    = "k8s-cirope-test"
  region  = "nyc1"
  version = "1.14.1-do.3"
  tags    = ["k8s-cirope-test"]

  node_pool {
    name       = "k8s-cirope-test-main"
    size       = "s-1vcpu-2gb"
    node_count = 1
    tags       = ["k8s-cirope-test"]
  }
}

resource "local_file" "kubernetes_config_test" {
  content  = digitalocean_kubernetes_cluster.k8s-cirope-test.kube_config.0.raw_config
  filename = "kubeconfig-test.yaml"
}
```

Is almost the same, but with a different Kubernetes version. I've tried with the same one as your example, but it fails with the same messages.

On creation it works, but when I execute a new `terraform apply` after the first one it fails.

Let me know if you need more info, thank you so much for looking at this.

Cheers.

**Comment by hcguersoy** [comment] 2019-06-04 14:49
Just for the records: I've the same error with the `1.4.0`.
It comes not on the first run there I create a K8s cluster on DO, but then I run it second time on an existing one.

**Comment by andrewsomething** [comment] 2019-06-04 15:13
Using the config provided by @francocatena, I can reproduce the issue. Beside the version, the main difference is that one config has tags while the other doesn't. Interestingly, removing the tags seems to allow the apply to be completed and the kubeconfig to be successfully written.

It's not clear to me how or why tags could cause an issue with the `local_file` provider yet but removing them seems to be a work around while we continue investigating.

**Comment by francocatena** [comment] 2019-06-06 20:00
@andrewsomething Thank you for that workaround, very hard to imagine that tags influences the config file, I wouldn't have tried that on my own!

Some behaviors that I remember now, the labels on the cluster were always taken as a "change", no matter how many times I applied it. Just mention it in case it helps.

**Comment by andrewsomething** [comment] 2019-08-29 19:36
I forgot to loop back around to this, but it should now be resolved. I can no longer reproduce the inconsistent plan issue when using tags. This was related to  https://github.com/terraform-providers/terraform-provider-digitalocean/pull/262

If you're still running into issue with a the most recent version of the provider, please feel free to reopen.

**Closed by andrewsomething** 2019-08-29 19:36 UTC
