### ISSUE TITLE
Terraform constantly tries to swap tags on droplets

### ISSUE THREAD

**Issue by inponomarev** [terraform-providers/terraform-provider-digitalocean#81] opened 2018-04-02 11:17 UTC
Hi, when I have droplets with two tags, terraform constantly tries to reorder the tags:
```
  ~ digitalocean_droplet.consul1
      tags.0: "consul_bootstrap" => "consul_instances"
      tags.1: "consul_instances" => "consul_bootstrap"
```
### Terraform Version
Terraform v0.11.5
+ provider.digitalocean v0.1.3

### Terraform Configuration Files
```hcl
resource "digitalocean_tag" "consul_instances" {
    name = "consul_instances"
} 
resource "digitalocean_tag" "consul_bootstrap" {
    name = "consul_bootstrap"
}

resource "digitalocean_droplet" "consul1" {
    image = "ubuntu-16-04-x64"
    name = "consul1"
    region = "fra1"
    size = "s-1vcpu-1gb"
    ssh_keys = ["${var.ssh_fingerprint}"]
    user_data = "${file("minimal.conf")}"
    tags   = ["${digitalocean_tag.consul_instances.id}", "${digitalocean_tag.consul_bootstrap.id}"]
}
```
### Expected Behavior
Tags order should not affect anything.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`, `terraform apply` and `terraform plan` again. Terraform will never show you an empty execution plan.

**Comment by wolverian** [comment] 2018-08-29 12:44
This might be a duplicate of #7.

**Comment by andrewsomething** [comment] 2018-08-29 16:10
Thanks for the report. As mentioned, this has already been reported in #7. The PR in #120 should resolve this behavior and will be included in the next release.

**Closed by andrewsomething** 2018-08-29 16:10 UTC
