### ISSUE TITLE
MySQL database cluster provisioning fails

### ISSUE THREAD

**Issue by rayrutjes** [terraform-providers/terraform-provider-digitalocean#361] opened 2020-01-21 08:20 UTC
### Terraform Version
0.20.19

### Affected Resource(s)
- digitalocean_database_cluster

### Terraform Configuration Files
```hcl
resource "digitalocean_database_cluster" "mysql" {
  name       = "mysql"
  engine     = "mysql"
  size       = var.mysql_droplets_size
  region     = var.region
  node_count = 1
}

resource "digitalocean_database_firewall" "mysql" {
  cluster_id = digitalocean_database_cluster.mysql.id

  rule {
    type  = "droplet"
    value = digitalocean_droplet.wordpress.id
  }
}

resource "digitalocean_database_user" "myproject" {
  cluster_id = digitalocean_database_cluster.mysql.id
  name       = "myproject"
}

resource "digitalocean_database_db" "myproject" {
  cluster_id = digitalocean_database_cluster.mysql.id
  name       = "myproject"
}

```

### Panic Output
```
Error: Error creating DatabaseCluster: Error trying to read DatabaseCluster state: GET https://api.digitalocean.com/v2/databases/d5ba7163-0368-4a02-9cb2-159fd6350c92: 404 (request "8fe96929-ae07-4c87-9315-99e4b7d73e9c") cluster not found


  on ../../modules/myproject/mysql.tf line 1, in resource "digitalocean_database_cluster" "mysql":
   1: resource "digitalocean_database_cluster" "mysql" {

```

### Expected Behavior
It should wait for the cluster to be created and move on.

### Actual Behavior
1. It crashes
2. The MySQL cluster is being created
3. When re-running `terraform apply` it tries to re-create it, but says the name is already in use, so the state was not persisted:
```
Error: Error creating DatabaseCluster: POST https://api.digitalocean.com/v2/databases: 422 (request "626f8a8b-3b02-48d6-9acf-50ca3436214d") cluster name is not available

  on ../../modules/myproject/mysql.tf line 1, in resource "digitalocean_database_cluster" "mysql":
   1: resource "digitalocean_database_cluster" "mysql"
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by eddiezane** [comment] 2020-01-21 20:45
@rayrutjes apologies that you ran into this.

I am unable to reproduce. Would you be able to elaborate or drill down to another case?

Also, could you please ensure that you're using the latest version of the provider (which is `
v1.12.0` as of now)?

Here's what I tested with:

```
provider "digitalocean" {}

data "digitalocean_droplet" "droplet" {
  name = "pool-udwnn15xa-kvsu"
}

resource "digitalocean_database_firewall" "mysql" {
  cluster_id = digitalocean_database_cluster.mysql.id

  rule {
    type  = "droplet"
    value = data.digitalocean_droplet.droplet.id
  }
}

resource "digitalocean_database_cluster" "mysql" {
  name       = "mysql"
  engine     = "mysql"
  size       = "db-s-1vcpu-1gb"
  region     = "sfo2"
  node_count = 1
}

resource "digitalocean_database_user" "myproject" {
  cluster_id = digitalocean_database_cluster.mysql.id
  name       = "myproject"
}

resource "digitalocean_database_db" "myproject" {
  cluster_id = digitalocean_database_cluster.mysql.id
  name       = "myproject"
}
```

**Comment by rayrutjes** [comment] 2020-01-21 21:46
I made an isolated test and it worked as expected.

The one time it failed, I had other resources failing to be built because ssh remote exec couldn't decrypt the SSH key. In this case, the database seems to be left in a state where the cluster isn't canceled but not persisted in the state.

I'll probably try to reproduce this in the following days.

**Comment by rayrutjes** [comment] 2020-01-22 06:37
This time I've got the following error:

```
Error: Provider produced inconsistent result after apply

When applying changes to
module.myproject.digitalocean_database_db.myproject, provider
"registry.terraform.io/-/digitalocean" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: timeout - last error: SSH authentication failed (ray@1x.x.x.x:22): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain



Error: Provider produced inconsistent result after apply

When applying changes to
module.myproject.digitalocean_database_user.myproject, provider
"registry.terraform.io/-/digitalocean" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

The SSH here timed out on a droplet, nothing to do with the MySQL cluster so not sure if it's related.

I might consider isolating the MySQL cluster in its own module to avoid side effects.

**Comment by lukoyanov** [comment] 2020-01-22 07:12
@rayrutjes last error could be related to https://github.com/terraform-providers/terraform-provider-digitalocean/issues/360#issuecomment-576937435

**Comment by rayrutjes** [comment] 2020-01-22 08:00
> @rayrutjes last error could be related to #360 (comment)

Indeed. Thanks for the update.

**Comment by eddiezane** [comment] 2020-01-28 16:39
Going to close this as a duplicate of #360. Let's track it there. I'll check in with the team for an update.

**Closed by eddiezane** 2020-01-28 16:39 UTC
