### ISSUE TITLE
Error creating tag: invalid character 'S' looking for beginning of value

### ISSUE THREAD

**Issue by holms** [terraform-providers/terraform-provider-digitalocean#124] opened 2018-08-29 11:32 UTC
Can't create tags

### Terraform Version
```
Terraform v0.11.7
+ provider.ansible v0.0.4
+ provider.aws v1.33.0
+ provider.cloudflare v1.2.0
+ provider.digitalocean v0.1.3
+ provider.mysql v1.1.0

```

### Affected Resource(s)
- digitalocean_tag

### Terraform Configuration Files
```hcl
variable "do_swarm_tags" {
    type = "list"
    description = "Digital Ocean tags for swarm cluster"
    default = [
        "type=app",
        "type=job"
    ]    
}

resource "digitalocean_tag" "type-job" {
  count = "${length(var.do_swarm_tags)}"
  name = "${element(var.do_swarm_tags, count.index)}"
}


```

### Debug Output

```
Error: Error applying plan:

2 error(s) occurred:

* digitalocean_tag.type-job[1]: 1 error(s) occurred:

* digitalocean_tag.type-job.1: Error creating tag: invalid character 'S' looking for beginning of value
* digitalocean_tag.type-job[0]: 1 error(s) occurred:

* digitalocean_tag.type-job.0: Error creating tag: invalid character 'S' looking for beginning of value

```

### Expected Behavior
Tag created

### Actual Behavior
Got error

### Steps to Reproduce
1. `terraform apply`

**Comment by paranoidd** [comment] 2018-08-30 17:12
For me this happens when DigitalOcean API responds with 503... and the "S" is from "Server Temporarily Unavailable"

**Comment by holms** [comment] 2018-09-03 07:15
You can reproduce this for sure. "=" gives trouble, do I need to escape it or something?

**Comment by andrewsomething** [comment] 2018-09-04 15:56
Thanks for the report. DigitalOcean tags can may only contain lowercase letters, numbers, colons, dashes, and underscores. `=` can not be used. But there is definitely a bug in the DigitalOcean API. We should not be returning an error that is not a property formatted JSON object. I've reported this internally at DO.

On the Terraform side, there are a few related improvements that will be in the next release of this provider.

* We will validate the tag name locally and error out before making the API call. See: https://github.com/terraform-providers/terraform-provider-digitalocean/blob/master/digitalocean/tags.go#L27
* We've pulled in a newer version of `godo` (the DigitalOcean go SDK) that will not choke on non-JSON errors.

While the DO API should not be returning them, this is useful for debugging in cases like this. This error:

    digitalocean_tag.type-job.0: Error creating tag: invalid character 'S' looking for beginning of value

Would become:

    digitalocean_tag.type-job.0: Error creating tag: Server Error

which at least makes it clear that the problem is on DO's end and not the user's.

**Closed by andrewsomething** 2018-09-04 15:56 UTC
